services:
  - type: web
    name: kibera-sp-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8001
      - key: CORS_ORIGINS
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /
